name: Build Release

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Release
      run: dotnet publish -c Release

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Locker-Release
        path: bin/Release/net8.0-windows/win-x64/publish/Locker.exe
        if-no-files-found: error
